### ISSUE TITLE
为什么代码不变每次训练得到的预测结果都不一样，

### ISSUE THREAD

**Issue by DanceGhost** [SharkFin-top/neuralprophet-doc-zh#2]

**Comment by AirFin** [comment]
设定随机seed即可



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月24日(周三) 下午5:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [SharkFin-top/neuralprophet-doc-zh] 为什么代码不变每次训练得到的预测结果都不一样， (Issue #2)




 
Closed #2.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
